site_name: ProxyBuilder
site_author: Sven Ruppert
google_analytics: ['UA-35462441-5', 'ProxyBuilder']


pages:
- Home: index.md
- DynamicProxy: dynamicproxy/index.md
- ObjectAdapter: objectadapter/index.md
- StaticProxy: staticproxy/index.md
- Projectinfos: projectinfos/index.md
- Additional Infos: additionalinfos/index.md
- About: about.md

#theme: readthedocs
#markdown_extensions: [fenced_code]
markdown_extensions:
    - toc:
        permalink: True